server {
    listen 80 default_server;
    server_name _;
    root /var/www/html;
    index index.php index.html;

    # Sunum surumunu gizle ama sahte, gercekci basliklar birak
    server_tokens off;
    absolute_redirect off;

    # --- FLAG 1 ---
    # Unutulmus bir "debug" basligi. curl -I ile gorunur.
    add_header X-Powered-By "PHP/8.2.4" always;
    add_header X-Debug-Token "FLAG{h3ad3rs_l34k_s3cr3ts}" always;

    location / {
        try_files $uri $uri/ =404;
    }

    # robots.txt'nin isaret ettigi dizin: yanlislikla dizin listeleme acik
    location /internal-backup/ {
        autoindex on;
    }

    # PHP dosyalarini PHP-FPM'e yonlendir.
    # DIKKAT: .bak uzantisi bu kaliba uymaz -> duz metin doner (FLAG 5).
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
